---
- name: Update web servers
  hosts: localhost
  gather_facts: true

  tasks:
  - name: Ensure apache is at the latest version
    shell: touch /tmp/AAABBCCC
    
  - name: Ensure bla
    command: "echo '{{ test }}' >> /tmp/AAABBCCC"
    
- name: Ensure bla23
  hosts: 127.0.0.1
  connection: local
  
  tasks:
    command: "ping -c 1 213.156.18.101"

