---
- name: Update web servers
  hosts: 127.0.0.1
  gather_facts: true

  tasks:
  - name: Ensure apache is at the latest version
    shell: touch /tmp/AAABBCCC
    
  - name: Ensure bla
    copy: content="{{ test }}" dest=/tmp/AAABBCCC

    
